force-app/main/default/objects/Habilidade__c/Habilidade__c.object-meta.xml
<CustomObject>
    <description>Objeto usado para armazenar as Habilidade dos Heróis ou Vilões.</description>
    <label>Habilidade</label>
    <nameField>
        <label>Habilidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Habilidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/HabilidadeContato__c.object-meta.xml
<CustomObject>
    <description>Usado como objeto de junção entre os objetos Contato e Habilidade</description>
    <label>Habilidade do Contato</label>
    <nameField>
        <displayFormat>HABIL-{0000}</displayFormat>
        <label>Habilidade do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Habilidade do Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Habilidade do Contato</relationshipLabel>
    <relationshipName>HabilidadeContato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Habilidade__c.field-meta.xml
<CustomField>
    <fullName>Habilidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Habilidade</label>
    <referenceTo>Habilidade__c</referenceTo>
    <relationshipLabel>Habilidade do Contato</relationshipLabel>
    <relationshipName>Habilidade_do_Contato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Grau de habilidade do Herói</description>
    <inlineHelpText>Grau de habilidade do Herói</inlineHelpText>
    <label>Level</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EditarContatoHabilControllerExt.cls
public with sharing class EditarContatoHabilControllerExt {

    private Contact contato;

    public List<HabilidadeContato__c> habilidades {get; private set;}

    public EditarContatoHabilControllerExt( ApexPages.StandardController controller ) {


        this.contato = (Contact) controller.getRecord();
        this.habilidades = [ SELECT id, Habilidade__r.Name, Level__c FROM HabilidadeContato__c WHERE Contato__c = :this.contato.Id ];

    }

    public Pagereference cancelar(){
        Pagereference pg = new Pagereference('/'+ this.contato.Id);
        pg.setRedirect(true);
        return pg;
    }

    public void salvar(){
        try{
            update this.contato;
            update this.habilidades;

            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.CONFIRM, 'Os registros foram atualizados!'));
        }catch( Exception e ){
            System.debug('>>> ERROR::'+e.getMessage());
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'O correu um erro no ao Atualizar registro'));
        }
    }

}