force-app/main/default/objects/Habilidade__c/Habilidade__c.object-meta.xml
<CustomObject>
    <description>Objeto usado para armazenar as Habilidade dos Heróis ou Vilões.</description>
    <label>Habilidade</label>
    <nameField>
        <label>Habilidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Habilidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/HabilidadeContato__c.object-meta.xml
<CustomObject>
    <description>Usado como objeto de junção entre os objetos Contato e Habilidade</description>
    <label>Habilidade do Contato</label>
    <nameField>
        <displayFormat>HABIL-{0000}</displayFormat>
        <label>Habilidade do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Habilidade do Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Habilidade do Contato</relationshipLabel>
    <relationshipName>HabilidadeContato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Habilidade__c.field-meta.xml
<CustomField>
    <fullName>Habilidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Habilidade</label>
    <referenceTo>Habilidade__c</referenceTo>
    <relationshipLabel>Habilidade do Contato</relationshipLabel>
    <relationshipName>Habilidade_do_Contato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContactCreateTask.cls
global class ContactCreateTask {
    
    @InvocableMethod(label = 'Cria Tarefa para o Contato')
    public static void ContactCreateTask( List<CreateTaskRequest> requests ){
        
        List<Id> lstContactIds = new List<Id>();
        for( CreateTaskRequest request : requests )
            lstContactIds.add(request.contactId);
        
        List<HabilidadeContato__c> lstHabContatos = [ select Id, Contato__c, Habilidade__r.Name from HabilidadeContato__c WHERE Contato__c IN :lstContactIds  ];
                
        Map<Id, List<String>> mapContatoHabilidades = new Map<Id, List<String>>(); 
        for( HabilidadeContato__c habilidadeContato : lstHabContatos ){    
            if( mapContatoHabilidades.containsKey( habilidadeContato.Contato__c ) ){
                mapContatoHabilidades.get( habilidadeContato.Contato__c ).add( habilidadeContato.Habilidade__r.Name );
            }else{
                mapContatoHabilidades.put( habilidadeContato.Contato__c, new List<String>{ habilidadeContato.Habilidade__r.Name } );
            }
        }
        
        if( !requests.isEmpty() )
        	createTasks( requests, mapContatoHabilidades );        
    }
    
    public static void createTasks( List<CreateTaskRequest> requests, Map<Id,List<String>> mapContatoHabilidades ){
        List<Task> tasksToInsert = new List<Task>();
        for( CreateTaskRequest request : requests ){
            Task tarefa = new Task();
            	tarefa.Subject 		= request.subject;
            	tarefa.WhoId   		= request.contactId;
            	tarefa.OwnerId 		= request.ownerId;
            	tarefa.Status  		= 'Open';
            	tarefa.Description 	= 'Por favor avalie este heroi. Suas habilidades são: '+ String.valueOf(mapContatoHabilidades.get(request.contactId));
            tasksToInsert.add(tarefa);
        }  
        
        if( !tasksToInsert.isEmpty() )
            insert tasksToInsert;
    }
    
    global class CreateTaskRequest {
        @InvocableVariable(required=true)
        global String contactId;
        @InvocableVariable(required=true)
        global String ownerId;
        @InvocableVariable
        global String subject;
    }

}