force-app/main/default/objects/BatalhaDoContato__c/BatalhaDoContato__c.object-meta.xml
<CustomObject>
    <description>Usado como junção entre os objetos contato e Batalha</description>
    <label>Batalha do Contato</label>
    <nameField>
        <displayFormat>Bat-{0000}</displayFormat>
        <label>Batalha do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batalhas do contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BatalhaDoContato__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Batalhas do contato</relationshipLabel>
    <relationshipName>BatalhasDoContato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/NivelDoHeroi__c.field-meta.xml
<CustomField>
    <fullName>NivelDoHeroi__c</fullName>
    <description>Nível de Senioridade do Herói</description>
    <inlineHelpText>Nível de Senioridade do Herói</inlineHelpText>
    <label>Nível do Herói</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aspira</fullName>
            </value>
            <value>
                <fullName>Júnior</fullName>
            </value>
            <value>
                <fullName>Pleno</fullName>
            </value>
            <value>
                <fullName>Sênior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/NomeDeGuerra__c.field-meta.xml
<CustomField>
    <fullName>NomeDeGuerra__c</fullName>
    <description>Nome de Guerra do Vilão e Herói.</description>
    <externalId>true</externalId>
    <inlineHelpText>Nome de Guerra do Vilão e Herói.</inlineHelpText>
    <label>Nome de Guerra</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Heroi.recordType-meta.xml
<RecordType>
    <fullName>Heroi</fullName>
    <active>true</active>
    <label>Herói</label>
</RecordType>

force-app/main/default/objects/Habilidade__c/Habilidade__c.object-meta.xml
<CustomObject>
    <description>Objeto usado para armazenar as Habilidade dos Heróis ou Vilões.</description>
    <label>Habilidade</label>
    <nameField>
        <label>Habilidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Habilidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/HabilidadeContato__c.object-meta.xml
<CustomObject>
    <description>Usado como objeto de junção entre os objetos Contato e Habilidade</description>
    <label>Habilidade do Contato</label>
    <nameField>
        <displayFormat>HABIL-{0000}</displayFormat>
        <label>Habilidade do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Habilidade do Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Habilidade do Contato</relationshipLabel>
    <relationshipName>HabilidadeContato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Habilidade__c.field-meta.xml
<CustomField>
    <fullName>Habilidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Habilidade</label>
    <referenceTo>Habilidade__c</referenceTo>
    <relationshipLabel>Habilidade do Contato</relationshipLabel>
    <relationshipName>Habilidade_do_Contato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Grau de habilidade do Herói</description>
    <inlineHelpText>Grau de habilidade do Herói</inlineHelpText>
    <label>Level</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GetAvailableHeroesIS.cls
@RestResource(urlMapping='/marvel/availableheroes/*')
global class GetAvailableHeroesIS {
    
    @HttpGet
    global static AvailableHeroes doGet(){
        Map<String, Hero> mapHerois = new Map<String,Hero>();
        List<HabilidadeContato__c> lstHabContatos = new List<HabilidadeContato__c>();
        String habilidadeParam = RestContext.request.params.get('habilidade');
        String nivelParam = RestContext.request.params.get('nivel');
        
        String dynamicQuery = 'select id, Contato__r.NomeDeGuerra__c, Contato__r.NivelDoHeroi__c, Habilidade__r.name, Level__c from HabilidadeContato__c where Contato__r.RecordType.DeveloperName = \'Heroi\' and Contato__c NOT IN ( select Contato__c from BatalhaDoContato__c)';
        if( !String.isBlank(habilidadeParam) ){
            List<String> habilidadesParam = habilidadeParam.split(',');
            dynamicQuery += ' and Habilidade__r.Name IN :habilidadesParam ';
        }
        if( !String.isBlank(nivelParam) ){
            List<String> niveisParam = nivelParam.split(',');
            dynamicQuery += ' and Contato__r.NivelDoHeroi__c IN :niveisParam ';
        } 
        
		lstHabContatos = Database.query(dynamicQuery);
        
        for( HabilidadeContato__c habilidadeContato : lstHabContatos ){
            Skill habilidade = new Skill( habilidadeContato.Habilidade__r.name, String.valueOf(habilidadeContato.Level__c) );
            Hero heroi;    
            
            if( !mapHerois.containsKey( habilidadeContato.Contato__r.NomeDeGuerra__c ) ){
                heroi = new Hero();
                heroi.nome 	= habilidadeContato.Contato__r.NomeDeGuerra__c;
                heroi.nivel = habilidadeContato.Contato__r.NivelDoHeroi__c;
                heroi.habilidades = new List<Skill>{ habilidade };
            }else{
                heroi = mapHerois.get( habilidadeContato.Contato__r.NomeDeGuerra__c );
                heroi.habilidades.add( habilidade );
            }
            mapHerois.put( habilidadeContato.Contato__r.NomeDeGuerra__c, heroi );
        }
        
        return new AvailableHeroes( mapHerois.values() );
        
    }
    
    global class AvailableHeroes{
        public List<Hero> herois;
        public Integer total;
        
        AvailableHeroes( List<Hero> herois ){
            this.herois = herois;
            this.total = herois.size();
        }
    }
    
    global class Hero{
        public String nome;
        public String nivel;
        public List<Skill> habilidades;
    }
    
    global class Skill{
        public String nome;
        public String nivel;
        
        Skill( String nome, String nivel ){
            this.nome = nome;
            this.nivel = nivel != null ? nivel : 'não avaliado';
        }
    }
    

}