force-app/main/default/objects/HabilidadeContato__c/HabilidadeContato__c.object-meta.xml
<CustomObject>
    <description>Usado como objeto de junção entre os objetos Contato e Habilidade</description>
    <label>Habilidade do Contato</label>
    <nameField>
        <displayFormat>HABIL-{0000}</displayFormat>
        <label>Habilidade do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Habilidade do Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Habilidade do Contato</relationshipLabel>
    <relationshipName>HabilidadeContato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AtualizaRankingBatchable.cls
public class AtualizaRankingBatchable implements Database.Batchable<SObject>{
    
    public AtualizaRankingBatchable() {}

    public AtualizaRankingBatchable(Integer minutes) {}

    public Database.QueryLocator start(Database.BatchableContext bc){
        System.debug('Start');

        return Database.getQueryLocator(
            'SELECT Id, Contato__c FROM HabilidadeContato__c ALL ROWS'
        );
    }

    public void execute(Database.BatchableContext bc, List<HabilidadeContato__c> records){
        System.debug('Execute');

        
        Set<Id> idsContato = new Set<Id>();
        for(HabilidadeContato__c habilidadeContato :  records){
            idsContato.add(habilidadeContato.Contato__c);
        }

        HabilidadeContatoBO.getInstance().atualizaRanking(idsContato);
    }

    public void finish(Database.BatchableContext bc){
        System.debug('Execute');

        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email
                            FROM AsyncApexJob
                            WHERE Id = : bc.getJobId()];

        System.debug('>>> JOB :: ' + job);
    }
}