force-app/main/default/objects/HabilidadeContato__c/HabilidadeContato__c.object-meta.xml
<CustomObject>
    <description>Usado como objeto de junção entre os objetos Contato e Habilidade</description>
    <label>Habilidade do Contato</label>
    <nameField>
        <displayFormat>HABIL-{0000}</displayFormat>
        <label>Habilidade do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Habilidade do Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Habilidade do Contato</relationshipLabel>
    <relationshipName>HabilidadeContato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Grau de habilidade do Herói</description>
    <inlineHelpText>Grau de habilidade do Herói</inlineHelpText>
    <label>Level</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AtualizaRankingScheduler.cls
public class AtualizaRankingScheduler implements Schedulable{
    
    public void execute(SchedulableContext sc) {
        run();
    }

    public void run(){
        Datetime now = System.now();

        List<HabilidadeContato__c> habilidadesContato = [SELECT Id, Contato__c 
                                                        FROM HabilidadeContato__c 
                                                        WHERE Level__c != null
                                                        AND SystemModstamp >= :now.addMinutes(-30) ALL ROWS];

        Set<Id> idsContato = new Set<Id>();
        for(HabilidadeContato__c habilidadeContato :  habilidadesContato){
            idsContato.add(habilidadeContato.Contato__c);
        }

        HabilidadeContatoBO.getInstance().atualizaRanking(idsContato);

    }
}