force-app/main/default/objects/HabilidadeContato__c/HabilidadeContato__c.object-meta.xml
<CustomObject>
    <description>Usado como objeto de junção entre os objetos Contato e Habilidade</description>
    <label>Habilidade do Contato</label>
    <nameField>
        <displayFormat>HABIL-{0000}</displayFormat>
        <label>Habilidade do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Habilidade do Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Habilidade do Contato</relationshipLabel>
    <relationshipName>HabilidadeContato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Grau de habilidade do Herói</description>
    <inlineHelpText>Grau de habilidade do Herói</inlineHelpText>
    <label>Level</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/NomeHabilidade__c.field-meta.xml
<CustomField>
    <fullName>NomeHabilidade__c</fullName>
    <description>Exibe o nome da Habilidade</description>
    <formula>Habilidade__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Exibe o nome da Habilidade</inlineHelpText>
    <label>Nome da Habilidade</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HabilidadeContatoBO.cls
public class HabilidadeContatoBO {

    private static final HabilidadeContatoBO instance = new HabilidadeContatoBO();

    private HabilidadeContatoBO() {

    }

    public static HabilidadeContatoBO getInstance(){
        return instance;
    }

    public void atualizaRanking(Set<Id> idsContato){
        Map<Id,Contact> mapContatosRevisarRanking = new Map<Id,Contact>([SELECT Id, 
                                                                        (SELECT Id, Name, Level__c 
                                                                        FROM HabilidadeContato__r 
                                                                        WHERE Level__c != null 
                                                                        ORDER BY Level__c DESC, NomeHabilidade__c) 
                                                                        FROM Contact 
                                                                        WHERE Id in : idsContato]);

        List<HabilidadeContato__c> habilidadesParaAtualizarRanking = new List<HabilidadeContato__c>();
            for(Contact contato : mapContatosRevisarRanking.values()){
                if(!contato.HabilidadeContato__r.isEmpty()){
                    Integer ranking = 1;
                    for(HabilidadeContato__c habilidadeContato : contato.HabilidadeContato__r){
                        habilidadeContato.Ranking__c = ranking++;
                        habilidadesParaAtualizarRanking.add(habilidadeContato);
                    }
                }
            }

        TriggerHandler.bypass('HabilidadeContatoTriggerHandler');
        update habilidadesParaAtualizarRanking;
        TriggerHandler.clearBypass('HabilidadeContatoTriggerHandler');
    }
}