force-app/main/default/objects/Contact/fields/DataDaAprovacao__c.field-meta.xml
<CustomField>
    <fullName>DataDaAprovacao__c</fullName>
    <label>Data da Avaliação do Treinamento</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/StatusCandidato__c.field-meta.xml
<CustomField>
    <fullName>StatusCandidato__c</fullName>
    <description>Mostra o Status do Candidato</description>
    <inlineHelpText>Mostra o Status do Candidato</inlineHelpText>
    <label>Status Candidato</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em Análise</fullName>
                <default>true</default>
                <label>Em Análise</label>
            </value>
            <value>
                <fullName>Reprovado na Análise</fullName>
            </value>
            <value>
                <fullName>Aguardando Aprovação p/ Treinamento</fullName>
            </value>
            <value>
                <fullName>Reprovado na Análise do Gestor</fullName>
            </value>
            <value>
                <fullName>Em Treinamento</fullName>
            </value>
            <value>
                <fullName>Reprovado no Treinamento</fullName>
            </value>
            <value>
                <fullName>Aprovado no Treinamento</fullName>
            </value>
            <value>
                <fullName>AprovadoDireto</fullName>
                <label>Aprovado Direto</label>
            </value>
            <value>
                <fullName>Aprovado Direto</fullName>
                <isActive>false</isActive>
                <label>Aprovado Direto</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CriaRelatorioPDFTrenamentoHeroiBachable.cls
public class CriaRelatorioPDFTrenamentoHeroiBachable implements Database.Batchable<SObject> {
  

    public Database.QueryLocator start(Database.BatchableContext bc){
        System.debug('>>> Start <<<');

        List<String> statusCandidato = new List<String>();

        Datetime lastHour = Datetime.now().addMinutes(-60);

        String query = 'SELECT Id, Name, DataDaAprovacao__c FROM Contact WHERE DataDaAprovacao__c >= ' +lastHour.format('yyyy-MM-dd')+'T'+lastHour.format('HH:mm:ss.SSSZ') +' AND StatusCandidato__c IN (\'Aprovado no Treinamento\', \'AprovadoDireto\')';
        System.debug('>>> QUERY :: '+query);


        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Contact> lstContatos){
        System.debug('Execute');

        System.debug('>>> lstContatos :: ' + lstContatos);        

        Set<Id> idsContato = new Set<Id>();
        for(Contact contato :  lstContatos){
            idsContato.add(contato.Id);
        }

        RelatorioPDFTreinamentoBO.getinstance().gerarPDFTreinamento(idsContato);
    }

    public void finish(Database.BatchableContext bc){
        System.debug('Finish');

        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email
                            FROM AsyncApexJob
                            WHERE Id = : bc.getJobId()];

        System.debug('>>> JOB :: ' + job);
    }
}