force-app/main/default/objects/Contact/fields/NivelDoHeroi__c.field-meta.xml
<CustomField>
    <fullName>NivelDoHeroi__c</fullName>
    <description>Nível de Senioridade do Herói</description>
    <inlineHelpText>Nível de Senioridade do Herói</inlineHelpText>
    <label>Nível do Herói</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aspira</fullName>
            </value>
            <value>
                <fullName>Júnior</fullName>
            </value>
            <value>
                <fullName>Pleno</fullName>
            </value>
            <value>
                <fullName>Sênior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Heroi.recordType-meta.xml
<RecordType>
    <fullName>Heroi</fullName>
    <active>true</active>
    <label>Herói</label>
</RecordType>

force-app/main/default/objects/HabilidadeContato__c/HabilidadeContato__c.object-meta.xml
<CustomObject>
    <description>Usado como objeto de junção entre os objetos Contato e Habilidade</description>
    <label>Habilidade do Contato</label>
    <nameField>
        <displayFormat>HABIL-{0000}</displayFormat>
        <label>Habilidade do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Habilidade do Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Grau de habilidade do Herói</description>
    <inlineHelpText>Grau de habilidade do Herói</inlineHelpText>
    <label>Level</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/NivelHeroi.cls
global class NivelHeroi {
    
    @InvocableMethod(label = 'Identifica Nivel do Heroi')
    public static List<Contact> identificaNivelHeroi(List<contactRequest> requests){
        
        List<Contact> contatos = new List<Contact>();
        
        for(contactRequest request : requests){
            Decimal media = 0;
            Decimal somaLevel = 0; 
            
            for(HabilidadeContato__c habilidadeContato : request.habilidadesContato){
                somaLevel += habilidadeContato.Level__c;
            }
            
            media = somaLevel/request.habilidadesContato.size();
            
            String nivel = '';
            if(media >= 80){
            	nivel = 'Sênior'; 	   
            }else if(media >= 40){
                nivel = 'Pleno';
            }else{
                nivel = 'Júnior';
            }            
           
            request.contact.NivelDoHeroi__c = nivel;
            contatos.add(request.contact);
        }
        
        update contatos;
		return contatos;        
    }
    
    global class contactRequest{
        @InvocableVariable(required=true)
        global Contact contact;
        @InvocableVariable(required=true)
        global List<HabilidadeContato__c> habilidadesContato;
    }
    
}