force-app/main/default/objects/Contact/fields/NomeDeGuerra__c.field-meta.xml
<CustomField>
    <fullName>NomeDeGuerra__c</fullName>
    <description>Nome de Guerra do Vilão e Herói.</description>
    <externalId>true</externalId>
    <inlineHelpText>Nome de Guerra do Vilão e Herói.</inlineHelpText>
    <label>Nome de Guerra</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Habilidade__c/Habilidade__c.object-meta.xml
<CustomObject>
    <description>Objeto usado para armazenar as Habilidade dos Heróis ou Vilões.</description>
    <label>Habilidade</label>
    <nameField>
        <label>Habilidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Habilidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/HabilidadeContato__c.object-meta.xml
<CustomObject>
    <description>Usado como objeto de junção entre os objetos Contato e Habilidade</description>
    <label>Habilidade do Contato</label>
    <nameField>
        <displayFormat>HABIL-{0000}</displayFormat>
        <label>Habilidade do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Habilidade do Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Habilidade do Contato</relationshipLabel>
    <relationshipName>HabilidadeContato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Habilidade__c.field-meta.xml
<CustomField>
    <fullName>Habilidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Habilidade</label>
    <referenceTo>Habilidade__c</referenceTo>
    <relationshipLabel>Habilidade do Contato</relationshipLabel>
    <relationshipName>Habilidade_do_Contato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Grau de habilidade do Herói</description>
    <inlineHelpText>Grau de habilidade do Herói</inlineHelpText>
    <label>Level</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EstudoSOQL.cls
public class EstudoSOQL {
    
    public static List<Contact> getAllContacts(){
        List<Contact> contatos = [SELECT ID, Name, CreatedDate FROM Contact];        
        return contatos;
        
        //OU
		//[SELECT ID, Name, CreatedDate FROM Contact];
    }
    
    public static Contact getContactById(Id contactId){
        Contact contato = [SELECT ID, Name, CreatedDate FROM Contact WHERE Id = :contactId]; 
        return contato;
        
        //List<Contact> contatos = [SELECT ID, Name, CreatedDate, (SELECT Id, Habilidade__r.Name FROM HabilidadeContato__r) FROM Contact WHERE Id = :contactId];
        //if(!conta)
    }
    
    public static Map<String, decimal> getAvgByContact(){
        AggregateResult[] results = [SELECT Contato__r.NomeDeGuerra__c NomeDeGuerra, AVG(Level__c) mediaLevel
										FROM  HabilidadeContato__c
										GROUP BY Contato__r.NomeDeGuerra__c
										HAVING AVG(Level__c) > 0
										ORDER BY AVG(Level__c) DESC];
        Map<String,Decimal> mapa = new map<String, Decimal>();
                                                     
        for(AggregateResult agResult : results){
        	String nomeGuerra = (String) agResult.get('NomeDeGuerra');
            Decimal mediaLevel = (Decimal) agResult.get('mediaLevel');
            mapa.put(nomeGuerra, mediaLevel);
        }
                                                     
        return mapa;
    }
    
    public static List<HabilidadeContato__c> getHabilidadesPorCOntatoOrHabilidades(String NomeDeGuerra, String nomeHabilidade){
        String query = 'SELECT Id, Habilidade__r.Name, Level__c, Contato__r.NomeDeGuerra__c FROM  HabilidadeContato__c WHERE ';
    
        if(!String.isEmpty(NomeDeGuerra)){
            query += 'Contato__r.NomeDeGuerra__c = :NomeDeGuerra';
                }else{
                    query += 'Habilidade__r.Name = :nomeHabilidade';
                }
        
        List<HabilidadeContato__c> HabilidadesDoContato = Database.query(query);
        
        return HabilidadesDoContato;
            
    }
    
}