force-app/main/default/objects/Contact/fields/NomeDeGuerra__c.field-meta.xml
<CustomField>
    <fullName>NomeDeGuerra__c</fullName>
    <description>Nome de Guerra do Vilão e Herói.</description>
    <externalId>true</externalId>
    <inlineHelpText>Nome de Guerra do Vilão e Herói.</inlineHelpText>
    <label>Nome de Guerra</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/StatusCandidato__c.field-meta.xml
<CustomField>
    <fullName>StatusCandidato__c</fullName>
    <description>Mostra o Status do Candidato</description>
    <inlineHelpText>Mostra o Status do Candidato</inlineHelpText>
    <label>Status Candidato</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em Análise</fullName>
                <default>true</default>
                <label>Em Análise</label>
            </value>
            <value>
                <fullName>Reprovado na Análise</fullName>
            </value>
            <value>
                <fullName>Aguardando Aprovação p/ Treinamento</fullName>
            </value>
            <value>
                <fullName>Reprovado na Análise do Gestor</fullName>
            </value>
            <value>
                <fullName>Em Treinamento</fullName>
            </value>
            <value>
                <fullName>Reprovado no Treinamento</fullName>
            </value>
            <value>
                <fullName>Aprovado no Treinamento</fullName>
            </value>
            <value>
                <fullName>AprovadoDireto</fullName>
                <label>Aprovado Direto</label>
            </value>
            <value>
                <fullName>Aprovado Direto</fullName>
                <isActive>false</isActive>
                <label>Aprovado Direto</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Habilidade__c/Habilidade__c.object-meta.xml
<CustomObject>
    <description>Objeto usado para armazenar as Habilidade dos Heróis ou Vilões.</description>
    <label>Habilidade</label>
    <nameField>
        <label>Habilidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Habilidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/HabilidadeContato__c.object-meta.xml
<CustomObject>
    <description>Usado como objeto de junção entre os objetos Contato e Habilidade</description>
    <label>Habilidade do Contato</label>
    <nameField>
        <displayFormat>HABIL-{0000}</displayFormat>
        <label>Habilidade do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Habilidade do Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Habilidade do Contato</relationshipLabel>
    <relationshipName>HabilidadeContato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Habilidade__c.field-meta.xml
<CustomField>
    <fullName>Habilidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Habilidade</label>
    <referenceTo>Habilidade__c</referenceTo>
    <relationshipLabel>Habilidade do Contato</relationshipLabel>
    <relationshipName>Habilidade_do_Contato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContactCreateTaskTest.cls
@isTest
public class ContactCreateTaskTest {
    
    @testSetup
    public static void setup(){
    
    	Contact capitaoAmerica = new Contact(FirstName='Steve', LastName='Rogers', NomeDeGuerra__c='Capitão América', StatusCandidato__c='Em Análise');
    	Contact viuvaNegra = new Contact(FirstName='Natasha', LastName='Romanoff', NomeDeGuerra__c='Viúva Negra', StatusCandidato__c='Em Análise');
        
        List<Contact> herois = new List<Contact> {capitaoAmerica, viuvaNegra};
        insert herois;
        
		Habilidade__c arteMarcial = new Habilidade__c(Name='Arte Marcial');
        Habilidade__c atirador = new Habilidade__c(Name='Atirador');
        Habilidade__c superForca = new Habilidade__c(Name='Super Força');
        
        List<Habilidade__c> habilidades = new List<Habilidade__c>{superForca, atirador, arteMarcial};
        insert habilidades;
        
        HabilidadeContato__c habilidadeContato1 = new HabilidadeContato__c();
        habilidadeContato1.Contato__c = capitaoAmerica.Id;
        habilidadeContato1.Habilidade__c = superForca.Id;
        
        HabilidadeContato__c habilidadeContato2 = new HabilidadeContato__c();
        habilidadeContato2.Contato__c = capitaoAmerica.Id;
        habilidadeContato2.Habilidade__c = arteMarcial.Id;
        
        HabilidadeContato__c habilidadeContato3 = new HabilidadeContato__c();
        habilidadeContato3.Contato__c = viuvaNegra.Id;
        habilidadeContato3.Habilidade__c = arteMarcial.Id;   

        List<HabilidadeContato__c> habilidadesContato = new List<HabilidadeContato__c>{habilidadeContato1, habilidadeContato2, habilidadeContato3};
        insert habilidadesContato;
    }  
    
    @isTest
    public static void ValidarCriacaoDeTask(){        
        List<Contact> contatos = [SELECT Id FROM contact WHERE StatusCandidato__c='Em Análise'];
        
        for(Contact contato: contatos){
            contato.StatusCandidato__c='AprovadoDireto';
        } 
        
        update contatos;
        
        List<task> tasks = [SELECT Id, Subject, Description FROM task ];
        
        system.assertEquals(2, tasks.size());
        system.assertEquals('Alocar contato em Batalha', tasks[0].Subject);
        system.assert(tasks[0].Description.contains('Super Força'));        
        
    }
}